const cfg = window.CONSULDOCE_CONFIG || {};
const { createClient } = window.supabase || {};
const sb = createClient ? createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY) : null;
const XLSX = window.XLSX;

const state = { session:null, profile:null, products:[], categories:[], cart:loadCart(), route:location.hash||'#/catalog', authMode:'login', adminTab:'orders', loading:false };
const app = document.getElementById('app');
const toastEl = document.getElementById('toast');

function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function money(n){return Number(n||0).toLocaleString('pt-PT',{minimumFractionDigits:0,maximumFractionDigits:0})+' un.';}
function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>toastEl.classList.remove('show'),3200)}
function loadCart(){try{return JSON.parse(localStorage.getItem('consuldoce_cart')||'{}')}catch{return {}}}
function saveCart(){localStorage.setItem('consuldoce_cart',JSON.stringify(state.cart))}
function cartCount(){return Object.values(state.cart).reduce((a,b)=>a+Number(b),0)}
function setRoute(r){location.hash=r;state.route=r;render()}
function logo(){return `<div class="brand"><div class="brand-mark">C</div><div><div class="brand-name">CONSULDOCE</div><div class="brand-sub">Gestão empresarial inteligente</div></div></div>`}
function header(){return `<header class="topbar"><div class="topbar-inner">${logo()}<div class="spacer"></div>${state.profile?`<div class="top-actions"><span class="desktop-only" style="font-size:11px;opacity:.8">${esc(state.profile.email||'')}</span>${state.profile.role==='admin'?`<button class="btn btn-secondary" onclick="setRoute('#/admin')">Administração</button>`:''}<button class="btn btn-secondary" onclick="setRoute('#/catalog')">Catálogo</button><button class="btn btn-primary" onclick="openCart()">Carrinho (${cartCount()})</button><button class="btn btn-secondary" onclick="logout()">Sair</button></div>`:''}</div></header>`}

function auth(){return `<div class="auth-shell"><div class="auth-card"><div class="auth-logo">${logo()}</div><div class="eyebrow">Acesso seguro</div><h1 class="h1">${state.authMode==='login'?'Entrar no catálogo':'Criar acesso de cliente'}</h1><p class="lead" style="margin-bottom:20px">${state.authMode==='login'?'Encomende a mercadoria disponível sem visualizar preços.':'Registe os dados da sua empresa para começar.'}</p><div class="tabs"><button class="tab ${state.authMode==='login'?'active':''}" onclick="state.authMode='login';render()">Entrar</button><button class="tab ${state.authMode==='signup'?'active':''}" onclick="state.authMode='signup';render()">Registar</button></div><form id="authForm" class="stack">${state.authMode==='signup'?`<div class="form-grid"><div class="form-group full"><label class="label">Nome / empresa</label><input class="field" name="full_name" required maxlength="150"></div><div class="form-group"><label class="label">NIF</label><input class="field" name="nif" required inputmode="numeric" maxlength="20"></div><div class="form-group"><label class="label">Morada</label><input class="field" name="address" required maxlength="250"></div></div>`:''}<div class="form-group"><label class="label">Email</label><input class="field" name="email" type="email" required autocomplete="email"></div><div class="form-group"><label class="label">Palavra-passe</label><input class="field" name="password" type="password" required minlength="8" autocomplete="${state.authMode==='login'?'current-password':'new-password'}"></div><button class="btn btn-primary" type="submit">${state.authMode==='login'?'Entrar':'Criar conta'}</button></form><div id="authMsg" style="margin-top:12px"></div><p class="footer-note">Catálogo privado B2B · Consuldoce</p></div></div>`}

async function doAuth(e){e.preventDefault();if(!sb)return;const f=new FormData(e.target);const email=f.get('email'),password=f.get('password');const msg=document.getElementById('authMsg');msg.innerHTML='';try{if(state.authMode==='login'){const {error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;toast('Sessão iniciada.')}else{const {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name:f.get('full_name'),nif:f.get('nif'),address:f.get('address')}}});if(error)throw error;if(!data.session){msg.innerHTML='<div class="notice">Conta criada. Verifique o email se a confirmação estiver ativa no Supabase e depois entre.</div>'}else toast('Conta criada.')} }catch(err){msg.innerHTML=`<div class="notice danger">${esc(err.message||'Não foi possível concluir.')}</div>`}}
async function logout(){await sb?.auth.signOut();state.session=null;state.profile=null;setRoute('#/login')}

async function loadSession(){if(!sb){state.route='#/login';return}const {data}=await sb.auth.getSession();state.session=data.session;if(state.session){await loadProfile();if(state.route==='#/login')state.route='#/catalog'}else state.route='#/login';sb.auth.onAuthStateChange(async (_e,s)=>{state.session=s;if(s){await loadProfile();if(state.route==='#/login')state.route='#/catalog'}else{state.profile=null;state.route='#/login'}render()});}
async function loadProfile(){const {data,error}=await sb.from('profiles').select('*').eq('id',state.session.user.id).single();if(!error)state.profile=data;else state.profile={id:state.session.user.id,email:state.session.user.email,role:'client'}}

async function loadProducts(){if(!sb||!state.session)return;const {data,error}=await sb.from('products').select('*').eq('active',true).order('category').order('name');if(error){toast(error.message);return}state.products=data||[];state.categories=[...new Set(state.products.map(p=>p.category).filter(Boolean))]}
function catalog(){const cats=state.categories.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');return `${header()}<main class="page"><div class="hero"><div><div class="eyebrow">Catálogo vivo</div><h1 class="h1">Produtos para encomenda</h1><p class="lead">Escolha as quantidades e envie a sua encomenda à Consuldoce. Os preços não são apresentados.</p></div><button class="btn btn-light" onclick="openOrders()">As minhas encomendas</button></div><div class="toolbar"><input id="search" class="field search" placeholder="Pesquisar por produto, referência ou código de barras..." oninput="filterProducts()"><select id="cat" class="field category" onchange="filterProducts()"><option value="">Todas as famílias</option>${cats}</select><button class="btn btn-primary" onclick="openCart()">Ver carrinho (${cartCount()})</button></div><div id="catalogGrid" class="catalog-grid"></div><div class="footer-note">Consuldoce · Catálogo B2B privado</div></main><div class="mobile-cart"><button class="btn btn-primary" onclick="openCart()">🛒 ${cartCount()}</button></div><div id="cartMount"></div><div id="ordersMount"></div>`}
function renderProducts(list=state.products){const grid=document.getElementById('catalogGrid');if(!grid)return;grid.innerHTML=list.length?list.map(productCard).join(''):'<div class="empty">Não foram encontrados produtos.</div>'}
function filterProducts(){const q=(document.getElementById('search')?.value||'').toLowerCase().trim(),c=document.getElementById('cat')?.value||'';renderProducts(state.products.filter(p=>(!c||p.category===c)&&(!q||[p.name,p.sku,p.barcode,p.short_description].filter(Boolean).join(' ').toLowerCase().includes(q))))}
function productCard(p){const qty=Number(state.cart[p.id]||0), max=p.track_stock?Number(p.stock_quantity||0):null;return `<article class="card"><div class="product-image">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}" loading="lazy">`:'<div class="placeholder">Imagem do produto<br>por adicionar</div>'}</div><div class="card-body"><span class="tag">${esc(p.category||'Produto')}</span><div class="product-name">${esc(p.name)}</div><div class="sku">Ref. ${esc(p.sku||'—')}${p.barcode?` · ${esc(p.barcode)}`:''}</div><div class="stock ${max===0?'off':''}">${max===null?'Disponível para encomenda':max>0?`${max} ${esc(p.unit||'un.')} disponíveis`:'Sem stock neste momento'}</div><div class="qty-row"><div class="qty"><button onclick="changeQty('${p.id}',-1)">−</button><input aria-label="Quantidade" value="${qty}" inputmode="numeric" onchange="setQty('${p.id}',this.value)"><button onclick="changeQty('${p.id}',1)">+</button></div><button class="btn btn-primary" ${max===0?'disabled':''} onclick="setQty('${p.id}',${qty+1})">Adicionar</button></div></div></article>`}
function setQty(id,v){const p=state.products.find(x=>x.id===id);if(!p)return;let q=Math.max(0,parseInt(v)||0);if(p.track_stock)q=Math.min(q,Number(p.stock_quantity||0));if(q)state.cart[id]=q;else delete state.cart[id];saveCart();renderProducts();updateCartButtons();}
function changeQty(id,d){setQty(id,(state.cart[id]||0)+d)}
function updateCartButtons(){document.querySelectorAll('.mobile-cart .btn').forEach(b=>b.textContent=`🛒 ${cartCount()}`);document.querySelectorAll('.top-actions .btn-primary').forEach(b=>b.textContent=`Carrinho (${cartCount()})`)}
function cartHtml(){const items=Object.entries(state.cart).map(([id,q])=>{const p=state.products.find(x=>x.id===id);if(!p)return '';return `<div class="cart-item"><img class="cart-thumb" src="${esc(p.image_url||'')}" onerror="this.style.display='none'"><div class="cart-meta"><div class="cart-name">${esc(p.name)}</div><div class="sku">Ref. ${esc(p.sku||'—')}</div><div class="cart-actions"><div class="qty"><button onclick="changeQty('${p.id}',-1);openCart()">−</button><input value="${q}" onchange="setQty('${p.id}',this.value);openCart()"><button onclick="changeQty('${p.id}',1);openCart()">+</button></div><strong>${money(q)}</strong></div></div></div>`}).join('');return `<div class="drawer open" onclick="if(event.target===this)closeCart()"><div class="drawer-panel"><div class="drawer-head"><div style="display:flex;justify-content:space-between;align-items:center"><div><div class="eyebrow">Encomenda</div><h2 style="margin:4px 0">Carrinho</h2></div><button class="btn btn-light" onclick="closeCart()">Fechar</button></div></div><div class="drawer-list">${items||'<div class="empty">O carrinho está vazio.</div>'}</div><div class="drawer-foot"><div style="display:flex;justify-content:space-between;margin-bottom:12px"><strong>Total de artigos</strong><strong>${cartCount()}</strong></div><button class="btn btn-primary" style="width:100%" ${cartCount()?'':'disabled'} onclick="openCheckout()">Finalizar encomenda</button></div></div></div>`}
function openCart(){document.getElementById('cartMount').innerHTML=cartHtml()}
function closeCart(){document.getElementById('cartMount').innerHTML=''}
function openCheckout(){closeCart();document.body.insertAdjacentHTML('beforeend',`<div id="checkoutModal" class="modal open"><div class="modal-card"><div class="modal-head"><div><div class="eyebrow">Confirmar</div><h2 style="margin:4px 0">Finalizar encomenda</h2></div><button class="btn btn-light" onclick="closeCheckout()">Fechar</button></div><div class="modal-body"><div class="notice success" style="margin-bottom:16px"><strong>${esc(state.profile?.full_name||'Cliente')}</strong><br>NIF ${esc(state.profile?.nif||'—')} · ${esc(state.profile?.address||'—')}<br><span class="hint">A encomenda será enviada para a Consuldoce.</span></div><div class="form-group"><label class="label">Observações (opcional)</label><textarea id="orderNotes" class="field" rows="4" maxlength="1000" placeholder="Ex.: entrega, preferência de acondicionamento... "></textarea></div><button class="btn btn-primary" style="width:100%;margin-top:16px" onclick="submitOrder()">Enviar encomenda</button></div></div></div>`)}
function closeCheckout(){document.getElementById('checkoutModal')?.remove()}
async function submitOrder(){if(!sb||!cartCount())return;const items=Object.entries(state.cart).map(([product_id,quantity])=>({product_id,quantity:Number(quantity)}));const notes=document.getElementById('orderNotes')?.value||'';try{const {data,error}=await sb.rpc('create_order',{p_items:items,p_notes:notes});if(error)throw error;const orderId=data;let emailOk=true;try{const r=await sb.functions.invoke('send-order-email',{body:{order_id:orderId}});if(r.error)emailOk=false}catch{emailOk=false}state.cart={};saveCart();closeCheckout();toast(emailOk?'Encomenda enviada com sucesso.':'Encomenda registada; o email será processado pela administração.');}catch(err){toast(err.message||'Não foi possível criar a encomenda.')}}

async function openOrders(){const {data,error}=await sb.from('orders').select('id,status,notes,created_at,order_items(product_name,sku,quantity)').eq('client_id',state.session.user.id).order('created_at',{ascending:false});if(error){toast(error.message);return}document.body.insertAdjacentHTML('beforeend',`<div id="ordersModal" class="modal open"><div class="modal-card"><div class="modal-head"><div><div class="eyebrow">Histórico</div><h2 style="margin:4px 0">As minhas encomendas</h2></div><button class="btn btn-light" onclick="document.getElementById('ordersModal').remove()">Fechar</button></div><div class="modal-body">${data?.length?data.map(o=>`<div class="panel" style="margin-bottom:10px"><div style="display:flex;justify-content:space-between"><strong>#${esc(o.id.slice(0,8))}</strong><span class="status ${o.status==='completed'?'done':o.status==='cancelled'?'cancelled':''}">${esc(o.status)}</span></div><div class="hint" style="margin:5px 0 10px">${new Date(o.created_at).toLocaleString('pt-PT')}</div>${(o.order_items||[]).map(i=>`<div style="display:flex;justify-content:space-between;font-size:12px;padding:5px 0"><span>${esc(i.product_name)} <span class="hint">(${esc(i.sku||'')})</span></span><strong>${i.quantity}</strong></div>`).join('')}</div>`).join(''):'<div class="empty">Ainda não existem encomendas.</div>'}</div></div></div>`)}

function admin(){return `${header()}<main class="page"><div class="hero"><div><div class="eyebrow">Backoffice</div><h1 class="h1">Administração</h1><p class="lead">Gerir catálogo, imagens, stock e encomendas.</p></div></div><div class="admin-layout"><aside class="side"><button class="${state.adminTab==='orders'?'active':''}" onclick="state.adminTab='orders';renderAdmin()">Encomendas</button><button class="${state.adminTab==='products'?'active':''}" onclick="state.adminTab='products';renderAdmin()">Produtos</button><button class="${state.adminTab==='import'?'active':''}" onclick="state.adminTab='import';renderAdmin()">Importar Excel</button><button class="${state.adminTab==='clients'?'active':''}" onclick="state.adminTab='clients';renderAdmin()">Clientes</button></aside><section id="adminContent"></section></div></main>`}
async function renderAdmin(){const c=document.getElementById('adminContent');if(!c)return;if(state.adminTab==='orders')await adminOrders(c);if(state.adminTab==='products')await adminProducts(c);if(state.adminTab==='import')adminImport(c);if(state.adminTab==='clients')await adminClients(c)}
async function adminOrders(c){const {data,error}=await sb.from('orders').select('id,status,notes,created_at,profiles(full_name,email,nif,address),order_items(product_name,sku,quantity)').order('created_at',{ascending:false});if(error){c.innerHTML=`<div class="panel danger">${esc(error.message)}</div>`;return}const counts={new:0,processing:0,completed:0,cancelled:0};(data||[]).forEach(o=>counts[o.status]=(counts[o.status]||0)+1);c.innerHTML=`<div class="stats"><div class="stat"><div class="hint">Novas</div><div class="stat-num">${counts.new}</div></div><div class="stat"><div class="hint">Em preparação</div><div class="stat-num">${counts.processing}</div></div><div class="stat"><div class="hint">Concluídas</div><div class="stat-num">${counts.completed}</div></div></div><div class="panel"><h2 class="panel-title">Encomendas</h2><p class="hint">Ações de estado e reenvio do email.</p><div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Cliente</th><th>Produtos</th><th>Estado</th><th>Ações</th></tr></thead><tbody>${(data||[]).map(o=>`<tr><td>${new Date(o.created_at).toLocaleString('pt-PT')}</td><td><strong>${esc(o.profiles?.full_name||'—')}</strong><br>${esc(o.profiles?.nif||'')}<br><span class="hint">${esc(o.profiles?.email||'')}</span></td><td>${(o.order_items||[]).map(i=>`${esc(i.product_name)} × ${i.quantity}`).join('<br>')}</td><td><select class="field" style="width:auto;padding:7px" onchange="updateOrderStatus('${o.id}',this.value)">${['new','processing','completed','cancelled'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select></td><td><button class="btn btn-light btn-small" onclick="resendEmail('${o.id}')">Reenviar email</button></td></tr>`).join('')}</tbody></table></div></div>`}
async function updateOrderStatus(id,status){const {error}=await sb.from('orders').update({status}).eq('id',id);if(error)toast(error.message);else toast('Estado atualizado.')}
async function resendEmail(id){const {error}=await sb.functions.invoke('send-order-email',{body:{order_id:id}});toast(error?'Não foi possível enviar o email.':'Email reenviado.')}

async function adminProducts(c){const {data,error}=await sb.from('products').select('*').order('category').order('name');if(error){c.innerHTML=`<div class="panel danger">${esc(error.message)}</div>`;return}window.__adminProducts=data||[];c.innerHTML=`<div class="panel"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap"><div><h2 class="panel-title">Produtos</h2><p class="hint">${data?.length||0} registos · sem preços no catálogo.</p></div><button class="btn btn-primary" onclick="openProductEditor()">Novo produto</button></div><div class="table-wrap" style="margin-top:12px"><table class="table"><thead><tr><th>Imagem</th><th>Produto</th><th>Família</th><th>Stock</th><th>Visível</th><th></th></tr></thead><tbody>${(data||[]).map(p=>`<tr><td>${p.image_url?`<img src="${esc(p.image_url)}" style="width:45px;height:45px;object-fit:contain;border-radius:8px;background:#f6f1f7">`:'—'}</td><td><strong>${esc(p.name)}</strong><br><span class="hint">${esc(p.sku)}</span></td><td>${esc(p.category||'')}</td><td>${p.track_stock?esc(p.stock_quantity):'—'}</td><td><span class="status ${p.active?'done':''}">${p.active?'Sim':'Não'}</span></td><td><button class="btn btn-light btn-small" onclick="openProductEditorById('${p.id}')">Editar</button></td></tr>`).join('')}</tbody></table></div></div>`}
function openProductEditorById(id){const p=window.__adminProducts?.find(x=>x.id===id)||{};openProductEditor(p)}
function openProductEditor(p={}){const obj=JSON.stringify(p).replace(/</g,'\\u003c');document.body.insertAdjacentHTML('beforeend',`<div id="productModal" class="modal open"><div class="modal-card"><div class="modal-head"><div><div class="eyebrow">Catálogo</div><h2 style="margin:4px 0">${p.id?'Editar produto':'Novo produto'}</h2></div><button class="btn btn-light" onclick="document.getElementById('productModal').remove()">Fechar</button></div><div class="modal-body"><form id="productForm" class="form-grid"><input type="hidden" name="id" value="${esc(p.id||'')}"><div class="form-group"><label class="label">Referência / SKU</label><input class="field" name="sku" required value="${esc(p.sku||'')}"></div><div class="form-group"><label class="label">Família</label><input class="field" name="category" value="${esc(p.category||'')}"></div><div class="form-group full"><label class="label">Nome do produto</label><input class="field" name="name" required value="${esc(p.name||'')}"></div><div class="form-group full"><label class="label">Descrição curta</label><input class="field" name="short_description" value="${esc(p.short_description||'')}"></div><div class="form-group"><label class="label">Stock atual</label><input class="field" name="stock_quantity" type="number" min="0" step="1" value="${esc(p.stock_quantity??0)}"></div><div class="form-group"><label class="label">Unidade</label><input class="field" name="unit" value="${esc(p.unit||'UNI')}"></div><div class="form-group"><label class="label">URL da imagem</label><input class="field" name="image_url" value="${esc(p.image_url||'')}" placeholder="https://..."></div><div class="form-group"><label class="label">Carregar imagem</label><input class="field" name="image_file" type="file" accept="image/*"></div><div class="form-group"><label class="label">Código de barras</label><input class="field" name="barcode" value="${esc(p.barcode||'')}"></div><div class="form-group"><label class="label">Opções</label><label style="font-size:12px"><input name="active" type="checkbox" ${p.active!==false?'checked':''}> Publicar no catálogo</label><label style="font-size:12px"><input name="track_stock" type="checkbox" ${p.track_stock?'checked':''}> Limitar encomenda ao stock</label></div><div class="form-group full"><button class="btn btn-primary" type="submit">Guardar produto</button></div></form></div></div></div>`);document.getElementById('productForm').addEventListener('submit',e=>saveProduct(e))}
async function saveProduct(e){e.preventDefault();const f=new FormData(e.target);const id=f.get('id');let imageUrl=f.get('image_url')||null;const file=f.get('image_file');try{if(file?.size){const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`products/${crypto.randomUUID()}.${ext}`;const up=await sb.storage.from('product-images').upload(path,file,{upsert:false,contentType:file.type});if(up.error)throw up.error;imageUrl=sb.storage.from('product-images').getPublicUrl(path).data.publicUrl}const payload={sku:String(f.get('sku')).trim(),category:String(f.get('category')||'').trim()||'Outros',name:String(f.get('name')).trim(),short_description:String(f.get('short_description')||'').trim(),stock_quantity:Number(f.get('stock_quantity')||0),unit:String(f.get('unit')||'UNI').trim(),image_url:imageUrl,barcode:String(f.get('barcode')||'').trim()||null,active:f.get('active')==='on',track_stock:f.get('track_stock')==='on'};let q=sb.from('products');const r=id?q.update(payload).eq('id',id):q.insert(payload);const {error}=await r;if(error)throw error;document.getElementById('productModal').remove();toast('Produto guardado.');renderAdmin()}catch(err){toast(err.message||'Erro ao guardar produto.')}}

function adminImport(c){c.innerHTML=`<div class="panel"><h2 class="panel-title">Importar dados Sage 50</h2><p class="hint">Aceita os dois ficheiros Excel fornecidos: listagem de artigos e inventário. A aplicação identifica automaticamente qual é qual.</p><div class="dropzone" style="margin:18px 0"><input id="excelFiles" class="file-input" type="file" accept=".xls,.xlsx" multiple><label for="excelFiles"><strong>Selecionar ficheiros .XLS / .XLSX</strong><br><span class="hint">Pode selecionar a listagem e o inventário ao mesmo tempo.</span></label></div><label style="display:block;font-size:12px;margin-bottom:15px"><input id="publishImported" type="checkbox" checked> Publicar automaticamente produtos normais com stock controlável</label><button class="btn btn-primary" onclick="importExcel()">Importar / atualizar catálogo</button><div id="importResult" style="margin-top:15px"></div><div class="notice" style="margin-top:18px"><strong>Mapeamento Sage:</strong> Ref_ → SKU · Produto → Nome · Descricao Curta → descrição · Familia → família · C_ Barras → código de barras · Uni → unidade · Existencias/Qnt_ Existente → stock.</div></div>`}
async function importExcel(){const files=[...(document.getElementById('excelFiles')?.files||[])];const out=document.getElementById('importResult');if(!files.length){out.innerHTML='<div class="notice danger">Selecione pelo menos um ficheiro.</div>';return}try{let listing=[],inventory=[];for(const file of files){const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:'array',cellDates:true});const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(ws,{defval:null});if(rows.some(r=>Object.prototype.hasOwnProperty.call(r,'Qnt_ Existente')))inventory=inventory.concat(rows);else if(rows.some(r=>Object.prototype.hasOwnProperty.call(r,'Produto')))listing=listing.concat(rows)}if(!listing.length){out.innerHTML='<div class="notice danger">Não foi reconhecida uma listagem de artigos.</div>';return}const invMap=new Map(inventory.map(r=>[String(r.Ref_??'').trim(),Number(r['Qnt_ Existente']||0)]));const publish=document.getElementById('publishImported')?.checked;const products=listing.map((r,i)=>{const sku=String(r.Ref_??'').trim();const category=String(r.Familia||r['Familia Completa']||'Outros').trim()||'Outros';const stock=invMap.has(sku)?invMap.get(sku):Number(r.Existencias||0);return {sku,name:String(r.Produto||r['Descricao Curta']||sku).trim(),short_description:String(r['Descricao Curta']||'').trim(),category,barcode:r['C_ Barras']?String(r['C_ Barras']).trim():null,unit:String(r.Uni||'UNI').trim(),stock_quantity:Math.max(0,stock),track_stock:true,active:publish && category.toUpperCase()!=='SERVIÇOS',sort_order:i}}).filter(p=>p.sku&&p.name);for(let i=0;i<products.length;i+=200){const batch=products.slice(i,i+200);const {error}=await sb.from('products').upsert(batch,{onConflict:'sku'});if(error)throw error}await loadProducts();out.innerHTML=`<div class="notice success">Importação concluída: <strong>${products.length}</strong> produtos atualizados${inventory.length?` e ${inventory.length} linhas de inventário lidas`:''}.</div>`;toast('Importação concluída.')}catch(err){out.innerHTML=`<div class="notice danger">${esc(err.message||'Falha na importação.')}</div>`}}

async function adminClients(c){const {data,error}=await sb.from('profiles').select('id,email,full_name,nif,address,role,created_at').order('created_at',{ascending:false});if(error){c.innerHTML=`<div class="panel danger">${esc(error.message)}</div>`;return}c.innerHTML=`<div class="panel"><h2 class="panel-title">Clientes</h2><p class="hint">Dados necessários à identificação e faturação do cliente.</p><div class="table-wrap"><table class="table"><thead><tr><th>Nome</th><th>NIF</th><th>Email</th><th>Morada</th><th>Registo</th></tr></thead><tbody>${(data||[]).map(p=>`<tr><td><strong>${esc(p.full_name||'—')}</strong></td><td>${esc(p.nif||'—')}</td><td>${esc(p.email||'—')}</td><td>${esc(p.address||'—')}</td><td>${new Date(p.created_at).toLocaleDateString('pt-PT')}</td></tr>`).join('')}</tbody></table></div></div>`}

async function render(){if(!state.session){app.innerHTML=auth();document.getElementById('authForm')?.addEventListener('submit',doAuth);return}if(state.route==='#/admin' && state.profile?.role!=='admin'){state.route='#/catalog'}if(state.route==='#/admin'){app.innerHTML=admin();await renderAdmin()}else{await loadProducts();app.innerHTML=catalog();renderProducts()}}
window.setRoute=setRoute;window.logout=logout;window.openCart=openCart;window.closeCart=closeCart;window.changeQty=changeQty;window.setQty=setQty;window.openCheckout=openCheckout;window.closeCheckout=closeCheckout;window.submitOrder=submitOrder;window.openOrders=openOrders;window.filterProducts=filterProducts;window.state=state;window.render=render;window.renderAdmin=renderAdmin;window.openProductEditor=openProductEditor;window.openProductEditorById=openProductEditorById;window.updateOrderStatus=updateOrderStatus;window.resendEmail=resendEmail;window.importExcel=importExcel;window.saveProduct=saveProduct;
window.addEventListener('hashchange',()=>{state.route=location.hash||'#/catalog';render()});
(async()=>{if(!cfg.SUPABASE_URL||cfg.SUPABASE_URL.includes('SEU-PROJETO')){app.innerHTML=`<div class="auth-shell"><div class="auth-card"><div class="eyebrow">Configuração</div><h1 class="h1">Ligar o catálogo ao Supabase</h1><p class="lead">Copie <strong>config.example.js</strong> para <strong>config.js</strong> e preencha o URL e a anon key pública do projeto Supabase.</p><div class="notice">Não coloque a <strong>service_role key</strong> no navegador.</div></div></div>`;return}await loadSession();await render()})();
